# Generated by Django 2.1.3 on 2018-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.CharField(max_length=2)),
                ('pay_date', models.DateField()),
            ],
        ),
    ]
