# Generated by Django 2.1.3 on 2018-11-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0002_auto_20181121_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='status',
            field=models.CharField(default='Unpaid', max_length=6),
        ),
    ]
