# Generated by Django 2.1.3 on 2018-11-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0003_installment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='week_no',
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('1', 'Unpaid'), ('2', 'Paid')], max_length=6),
        ),
    ]
