# Generated by Django 2.1.3 on 2018-11-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_remove_reference_savings'),
        ('loan', '0010_remove_loan_installment'),
        ('installment', '0004_auto_20181123_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='status',
        ),
        migrations.AddField(
            model_name='installment',
            name='installment',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='installment',
            name='name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loan.Loan'),
        ),
        migrations.AddField(
            model_name='installment',
            name='pay_to',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Reference'),
        ),
    ]
