# Generated by Django 2.1.3 on 2018-12-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_remove_loan_installment'),
        ('installment', '0009_auto_20181214_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaninstallment',
            name='name',
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loan.Loan'),
        ),
    ]
