# Generated by Django 2.1.3 on 2018-12-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0010_auto_20181214_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninstallment',
            name='name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loan.Loan'),
        ),
    ]
