# Generated by Django 2.1.3 on 2018-11-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='reference',
            field=models.ForeignKey(choices=[(1, 'Tajibul Mir'), (2, 'Sohel Rana')], null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Reference'),
        ),
    ]
