# Generated by Django 2.1.3 on 2018-11-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20181116_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='reference',
            field=models.ForeignKey(choices=[('Tajibul Mir', 'Tajibul Mir'), ('Sohel Rana', 'Sohel Rana')], null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Reference'),
        ),
    ]
