# Generated by Django 2.1.3 on 2018-11-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20181116_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment_no',
            field=models.CharField(default=3, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(default=1, max_length=10, null=True),
        ),
    ]
