# Generated by Django 2.1.3 on 2018-11-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0001_initial'),
        ('loan', '0008_auto_20181121_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='installment_no',
        ),
        migrations.AddField(
            model_name='loan',
            name='installment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='installment.Installment'),
        ),
    ]
