# Generated by Django 2.1.3 on 2018-11-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_auto_20181121_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='installment',
        ),
    ]
