# Generated by Django 2.1.3 on 2018-11-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_reference_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='savings',
        ),
    ]
